### ISSUE TITLE
Dropping container when wrong runtime

### ISSUE THREAD

**Issue by tidylobster** [Hydrospheredata/hydro-serving#178]
If runtime wasn't set correctly on creating application, it might cause problems with corresponding docker container. Invoking that application will likely fail, but moreover, user will not know, what happened, as there is no proper warning message. After invocation, runtime container will be dropped(removed).

**Comment by KineticCookie** [comment]
Note: there is already an API that returns list of runtimes for a `modelType`. However, since the field is set by a user for both models and runtimes, it doesn't guarantee that runtime actually won't crash on initialization.

Ultimately we need a container validation after initialization mechanism, so we could interrupt the creation of app services and remove the app.
