### ISSUE TITLE
there is some compile error，can you have a look

### ISSUE THREAD

**Issue by polarBearGit** [Hydrospheredata/hydro-serving#187]
hello, there is some compile error，can you have a look,thx

![image](https://user-images.githubusercontent.com/11705236/43125889-d95739d2-8f5d-11e8-98b9-15611ca89ddd.png)

**Comment by KineticCookie** [comment]
Hello @polarBearGit 
Seems like your IDE can't find a generated code.
You need to perform `sbt compile` in order to generate it.
Then you are ready to go.

BTW, If you just want to deploy a demo instance, it's better to use provided docker-compose.

Feel free to leave feedback or ask questions in our gitter channel https://gitter.im/Hydrospheredata/hydro-serving

**Comment by KineticCookie** [comment]
closed since build and codegen was changed
