### ISSUE TITLE
how do you increase the number of instances of a Model?

### ISSUE THREAD

**Issue by ravimadhusudhan8** [Hydrospheredata/hydro-serving#232]

**Comment by tidylobster** [comment]
Hi, @ravimadhusudhan8. This depends on how you've instantiated serving. If you've done this with docker-compose, then this option is not available for you. If you've done this on the Kubernetes cluster, then you can scale a deployment. Currently application deployment have the following name: `r{runtime_id}m{model_id}e{environment_id}`. So, for example it might be something like `r1m1e0`. If you have multiple applications then this might be a little problematic since it's hard to identify which of the application has which name. We are aware of this and will improve the naming soon. Possible workaround for now is to identify which of the deployment you want to scale by looking at its pod logs and then apply the scaling:

```
$ kubectl scale --replicas=2 deployment/r1m1e0
```

**Comment by ravimadhusudhan8** [comment]
Thanks for the feedback. Will work on using Kubernetes cluster and will apply your suggestions.
