### ISSUE TITLE
error: Error occurred while preparing cluster: 'current-cluster'

### ISSUE THREAD

**Issue by albertnanda** [Hydrospheredata/hydro-serving#257]
getting error whenever i issue any hs command:
error: Error occurred while preparing cluster: 'current-cluster'

**Comment by chenchaiah-chinna** [comment]
Install the latest CLI release candidate
pip install hs==2.0.0rc3

**Comment by ravimadhusudhan8** [comment]
On K8 
- pip install hs==2.0.0rc2 works 

- not pip install hs==2.0.0rc3

**Comment by tidylobster** [comment]
This issue is related to the backward incompatibility with the newest cli architecture. If you had created cluster entities with the previous cli version, you would probably experience this. To fix, remove all previously created meta information `rm -rf ~/.hs-home` and try again with the hs==2.0.0rc3

**Comment by KineticCookie** [comment]
Closed since hs==2.0.0 contains fix for this
