### ISSUE TITLE
Removing Models and Applications

### ISSUE THREAD

**Issue by iakrevetkho** [Hydrospheredata/hydro-serving#280]
Hello!

I run Hydrosphere.io with build info:
![image](https://user-images.githubusercontent.com/40871973/58861034-2980fd80-86b6-11e9-864f-c753eb61f1a8.png)

on CentOS 7 inside VirtualBox.

Hydrosphere.io installed in Docker.

1. When trying to delete a model that is registered in the application, an error 400 occurred. After deleting the application that used the model, the deletion was successful. I propose to make a warning window with the question: "Delete the application using this model?"
2. When you delete a model or application, disk space is not reduced. It seems that the record about the model and the application is simply deleted, but their build is not deleted.

Thank you!

**Comment by KineticCookie** [comment]
Hi @iakrevetkho 
Thank you for the feedback.
1. This is somewhat planned behaviour. User can't just delete a model without cleaning it up manually, otherwise one could just simply destroy a running ML pipeline. Concerning the error message, I agree with you - it should be more informative. We will improve it in the next release.
2. Built models are stored in docker registry as images. When you delete the model we actually delete our metadata about it. But in fact the image itself remains untouched. We designed this behavior, keeping in mind that 
 a. model files could be useful in the future
 b. you can recover models after failure
 c. well it's an image, and theoretically you can customize it.
